version: 2
jobs:
  test:
    working_directory: /mnt
    docker:
      - image: appsilon/shiny.semantic-build:3.4.1
    steps:
      - checkout
      - run:
          name: Run devtools check
          command: "R -e 'results <- devtools::check(); stopifnot(length(results$errors) == 0 & length(results$warnings) == 0 & length(results$notes) == 0)'"
      - store_artifacts:
          path: ..Rcheck
          prefix: tests
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
