# Implementing Steps element from fomantic
# https://fomantic-ui.com/elements/step.html


#' @rdname single_step
#' @import shiny
#' @export
single_step <- function(id, title, description = NULL, icon_class = NULL,
                        class = NULL) {
    step_icon <- if (is.null(icon_class)) NULL else tags$i(class = paste(icon_class, "icon"))
    step_description <- if (is.null(description)) NULL else shiny::div(
        class = "description",
        description
    )
    step_title <- shiny::div(class = "title", title)
    step_class <- ifelse(
        is.null(class),
        "step",
        sprintf("%s step", class)
    )

    shiny::div(
        id = id,
        class = step_class,
        step_icon,
        shiny::div(
            class = "content",
            step_title,
            step_description)
    )
}


#' Show, Hide or Remove Semantic UI modal
#'
#' This displays a hidden Semantic UI modal.
#'
#' @param id ID of the Steps that will be displayed.
#' @param steps_list A list of steps generated by single_steps.
#' @param class (Optional) A character string with the semantic class to be
#' added to the steps element.
#' @seealso single_steps
#' @rdname steps
#' @import shiny
#' @export
steps <- function(id, steps_list, class = NULL) {
    steps_class <- ifelse(
        test = is.null(class),
        yes = "ui steps",
        no = sprintf("ui %s steps", class)
    )
    shiny::div(
        class = steps_class,
        steps_list
        # lapply(steps_list, function(step) step)
    )
}

# Example usage
# UI 
# steps(list(
#     single_step("Step 1", "Make a call", "phone", TRUE),
#     single_step("Step 2", "Order some food", "leaf"),
#     single_step("Step 3", "Feed the bird", "kiwi bird")
#     ),
#     class = "ordered"
#     )

#' @rdname toggle_step_state
#' @export
toggle_step_state <- function(id, state = TRUE, asis = FALSE) {
    session <- shiny::getDefaultReactiveDomain()
    # Make sure set_attribute_by_id works with namespaces (shiny modules)
    id <- ifelse(
        inherits(session, "session_proxy") && !asis,
        session$ns(id),
        id
    )
    parameters <- list("step_id" = id, "state" = state)
    session$sendCustomMessage("toggle_step_state", parameters)
}